### ISSUE TITLE
Add PWA Support

### ISSUE THREAD

**Issue by aniket-magadum** [RomainMazB/octobercms-tailwindcss-boilerplate#1]
I would like to have a integration with [workbox-webpack-plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin).
I have tried this integration earlier using laravel mix but had a problem with scope as service workers are required to be served from the root of the project like https://example.com/sw.js. There are workarounds this by adding a route which I find very unclean. I personally think someone with a better understanding with webpack can solve this issue.

I would like to thankyou for this boilerplate. It was something I wish to have since long

**Comment by RomainMazB** [comment]
Hi @aniket-magadum ,
I don't really understand what your issue with this package is (or isn't?).

I'm afraid I'm not the guy you are looking for: yeah I wrote this package, and I will update it with many features I have already in my mind which will be kind of awesome I think but actually I'm not a big professionnel of webpack ( I'm a backend guy :smile: ), the loader I wrote for this package was the first one for me (there is so many packages out there, it's hard to find something you need which doesn't exists).

If I can help let me know but if you are asking me to make a support for my package to workbox-webpack-plugin... I didn't have hear about this plugin before today sorry.

**Comment by aniket-magadum** [comment]
@RomainMazB there is nothing wrong with the package . I am making a feature request have you read or know what service workers are?

**Comment by RomainMazB** [comment]
@aniket-magadum I have read about it but I'm not comfortable with it and have never used one of it, what would be the benefits to use a web-worker with my package?

Maybe one day I'll make a deeper look at it but for now I don't need it and have a mission to accomplish.

If I may help you in the understanding of my package to implement WPA Support, it will be a pleasure.
