### ISSUE TITLE
Toxic `return $theme_name . '-src';` in Plugin.php

### ISSUE THREAD

**Issue by kosmonowt** [RomainMazB/octobercms-tailwindcss-boilerplate#14]
Hi, this line above in the PHP throws errors even in blank themes.
It basically brakes the CMS page.

**Comment by RomainMazB** [comment]
Solved from the OctoberCMS's slack channel: the marketplace documentation was not up to date.

I'll provide a more friendly error in the next version to notice the users a full blank theme can't be built.

The blank theme I talk about in the documentation is the one present in the boilerplate folder named `blank-src`
