### ISSUE TITLE
Alpine JS integration in tailwind boilerplate

### ISSUE THREAD

**Issue by Habinho** [RomainMazB/octobercms-tailwindcss-boilerplate#19]
Can you please give some infos on how to integrate alpinejs in your tailwind boilerplate. I'm constantly have errors on npm run watch and I guess it's because of the alpine js code in my partials. Thx

**Comment by RomainMazB** [comment]
Hi @habinho,
I never used AlpineJS with the boilerplate, could you please copy/paste the npm error or provide a basic example repository (only your theme folder) so I can reproduce and fix it?

**Comment by RomainMazB** [comment]
@Habinho I've just created a theme using AlpineJS and didn't met found any issue, could you provide a repo to reproduce?

**Comment by RomainMazB** [comment]
Closing this as no response since 6 months.
Feel free to re-open if you face this again.
