### ISSUE TITLE
Javascript not running

### ISSUE THREAD

**Issue by RobinL88** [RomainMazB/octobercms-tailwindcss-boilerplate#27]
Hey, 

I have a problem with javascript not running from the JS files.

I added a button and function to do some testing. But when I click the button I get the error 
Uncaught ReferenceError: myFunction is not defined at HTMLButtonElement.onclick

When I add the script to the page itself it works.

I have no idea where to look or what to do.
Can you point me in the right direction?
What info do I need to provide?

**Comment by RomainMazB** [comment]
Hi @robinl88 !
I'm using JavaScript in all my themes that use this boilerplate and I'm not facing anything that match your issue.

Did you correctly imported the theme.js file inside your layout? The default `blank-src` theme is well configured to import it here as an example: https://github.com/RomainMazB/octobercms-tailwindcss-boilerplate/blob/master/blank-src/layouts/default.htm#L36

**Comment by RobinL88** [comment]
Hey,

It is exactly the same.
I think the problem lays when the theme.js gets compiled.


Edit:
I created a blank theme.
Added myFunction to app.js under Application and it does not work.


This is how it looks in the theme.js file.

```
/***/ "../blank-src/assets/javascript/app.js":
/*!*********************************************!*\
  !*** ../blank-src/assets/javascript/app.js ***!
  \*********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("/*\n * Needed for October's framework\n */\nwindow.jQuery = __webpack_require__(/*! jquery */ \"../blank-src/node_modules/jquery/dist/jquery.js\")\n\n /*\n * Application\n */\n\n function myFunction() {\n alert(\"Hello World!\");\n }\n\n\n//# sourceURL=webpack:///../blank-src/assets/javascript/app.js?");

/***/ }),
```

**Comment by RomainMazB** [comment]
The compiled file looks good to me. It can be curious when you start to work with webpack but it's the way it works.

In the backend settings, did you correctly choose the blank theme and not the blank-src one?

**Comment by RobinL88** [comment]
At the moment I am thinking the problem lays with my outdated knowledge of making websites.
The problem has to be in the coding of the site. Not the boilerplate.

Thanks for the help.
